package com.arkaitem.items;

public interface ICustomAdds {
    String CANT_DROP = "CANT_DROP";
    String TREE_FELLER = "TREE_FELLER";
    String NO_DISCARD = "NO_DISCARD";
    String KEEP_ON_DEATH = "KEEP_ON_DEATH";
    String UNBREAKABLE = "UNBREAKABLE";
    String NO_FALL_DAMAGE = "NO_FALL_DAMAGE";
    String GIVE_POTION = "GIVE_POTION";
    String KILL_GIVE_POTION = "KILL_GIVE_POTION";
    String DEATH_CHANCE_TP = "DEATH_CHANCE_TP";
    String TELEPORT_ON_ATTACK = "TELEPORT_ON_ATTACK";
    String HIT_EFFECT = "HIT_EFFECT";
    String SELF_EFFECT = "SELF_EFFECT";
    String SPAWN_LIGHTNING = "SPAWN_LIGHTNING";
    String SPAWN_HEAD_ON_KILL = "SPAWN_HEAD_ON_KILL";
    String STEAL_LIFE = "STEAL_LIFE";
    String STEAL_MONEY = "STEAL_MONEY";
    String VIEW_ON_CHEST = "VIEW_ON_CHEST";
    String MINE_AREA = "MINE_AREA";
    String BLOCK_COLUMN = "BLOCK_COLUMN";
    String SELL_CHEST_CONTENTS = "SELL_CHEST_CONTENTS";
    String CONSUMABLE = "CONSUMABLE";
    String CONSUMABLE_GIVE_POTION = "CONSUMABLE_GIVE_POTION";
    String CONSUMABLE_USE_COMMAND = "CONSUMABLE_USE_COMMAND";
    String EXECUTE_COMMAND_ON_KILL = "EXECUTE_COMMAND_ON_KILL";
    String HIDE_PLAYER_NAME = "HIDE_PLAYER_NAME";
    String MULTIPLICATEUR = "MULTIPLICATEUR";
}
