name: Arkaitem
version: 1.0
description: Plugin de création d'items customs avec des effets visuels avancés
author: Hugo PIAT-LILLO
main: com.arkaitem.Program
api-version: 1.8.8
commands:
  arkaitem:
    description: Commande principale pour gérer les items customs
    usage: /arkaitem <give/menu/enable/disable/reload>
    permission: arkaitem.admin
  arkaitemcraft:
    description: Commande de gestion des crafts customs
    usage: /arkaitem <open/add/remove>
    permission: arkaitem.admin
permissions:
  arkaitem.admin:
    default: op